### PR TITLE
Added issue.bunsen & motd.bunsen

### PR DESCRIPTION
**Pull request by Head-on-a-Stick**
Added custom /etc/{issue,motd}

See https://forums.bunsenlabs.org/viewtopic.php?id=3153

### CODE REVIEW

**Comment by 2ion** [comment]
Two remarks:

* In issue.bunsen, the logo is way too high in terms of pixel space.
  Let's keep it as "BunsenLabs Linux 8 \n \l". "GNU" is mostly a Debian
  thing anyway.

* In motd.bunsen, let's keep the default or choose something less l33t.

**Comment by Head-on-a-Stick** [comment]
> the logo is way too high in terms of pixel space.
OK, johnraff mentioned a similar issue.

> Let's keep it as "BunsenLabs Linux 8 \n \l". "GNU" is mostly a Debian thing anyway.
I would prefer just "BunsenLabs 8 \n \l", if the "GNU" bit is dropped then so should the "Linux" bit else it may be seen as taking preference in that particular debate.

> In motd.bunsen, let's keep the default or choose something less l33t.
Very well. I just though it was funny.

**Comment by johnraff** [comment]
1) Have to agree with @2ion on the size of that flame. With my current font it occupies the whole 900px height of my screen.

2)
> I would prefer just "BunsenLabs 8 \n \l", if the "GNU" bit is dropped then so should the "Linux" bit else it may be seen as taking preference in that particular debate.

Well, you could just as well say that adding the GNU was taking a side in the debate too. My preference would be to keep "Linux" in the name, either with or without "GNU" (although the quantity of GNU material in most Linux distros is quite large). We're not a BSD-based setup after all.

3) Sorry @Head-on-a-Stick but I agree with 2ion about motd.bunsen too.
In fact, I think there is a discussion to be had over how much we should be branding BL as something other than Debian.

4) Technical note: @Head-on-a-Stick are you proposing that those files should be used by default? If so I don't think just installing them will be enough - we'd have to do another divert-and-symlink operation.

**Comment by Head-on-a-Stick** [comment]
>  I think there is a discussion to be had over how much we should be branding BL as something other than Debian.

Yes, that is a very good point. I had just considered this as a sort of "easter egg" for the users to give them a smile if they have to switch to the console but on further consideration perhaps this is not such a good idea.

I am going to go ahead and close this, thank you for the input guys and sorry for the noise.

**Pull request closed without merging**
